# .github/workflows/release.yml
name: release
on:
  push:
    tags: ['v*']
  workflow_dispatch: {}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Ensure tag matches package.json version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "Tag v$TAG does not match package.json version $PKG_VERSION"
            exit 1
          fi

      - name: Verify npm auth
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PICKER }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PICKER }}
